##
# should-assert cspell configuration
#
# See https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell#customization
---

version : 0.2

language           : en     # Current active spelling language
minWordLength      : 3      # The minimum length of a word before it is checked
allowCompoundWords : false  # Allow compound words?

# List of globs to specify which files are to be ignored
ignorePaths:
    - "**/node_modules/**"
    - "**/vscode-extension/**"
    - "**/.git/**"
    - "**/.git*"
    - .vscode
    - megalinter
    - megalinter-reports
    - package-lock.json
    - report

# List of the names of the dictionaries to use
# See: https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell#Dictionaries
dictionaries:
    - companies     # List of well-known companies
    - softwareTerms # Common software terms
    - python        # Python-specific words

# Definition details for custom dictionaries used above
dictionaryDefinitions: []

# List of words to be always considered correct
words:
    - DEVSKIM
    - JSONLINT
    - npx
    - osxsecurity
    - utf

# List of words to be always considered incorrect
flagWords: []

# List of words to be ignored (even if they are in the flagWords)
ignoreWords: []
